config/routes.rb
Express::Application.routes.draw do
  resources :candidate_stances

  resources :baselines

  resources :votes

  devise_for :voters do
    match '/login' => 'devise/sessions#new', :as => :login
    match '/logout' => 'devise/sessions#destroy', :as => :logout
  end

  resources :issue_stances

  resources :stances

  resources :issues

  resources :parties

  resources :candidates

  resources :elections do
    member do
      get 'poll_results'
    end
    resources :votes
  end

  resources :offices

  resources :organizations
  
  match "build/:action/:id" => "blueprints"
  
  root :to => "elections#index"

end

app/models/baseline.rb
class Baseline < ActiveRecord::Base
  belongs_to :election
  belongs_to :voter
  
  scope :current, :conditions => {:current => true}
  scope :by, lambda { |voter| {:conditions => {:voter_id => voter.id}} }
end

app/models/candidate.rb
class Candidate < ActiveRecord::Base
  belongs_to :election
  has_one :office, :through => :election
  has_one :organization, :through => :office
  has_many :votes
  has_many :candidate_stances
  # has_many :issue_stances
  
  def name_and_office
    name + " for " + election.office.name
  end
  
  def chosen_by? voter
    votes.current.by(voter).first.andand.support.andand.>(election.baselines.current.by(voter).first.andand.level)
  end
  
  def support
    if election.votes.current.count == 0
      total_votes = 1
    else
      total_votes = election.votes.current.map(&:voter).uniq.count
    end
    100.0 * votes.current.count / total_votes
  end
end

app/models/candidate_stance.rb
class CandidateStance < ActiveRecord::Base
  belongs_to :candidate
  belongs_to :issue_stance
  has_one :issue, :through => :issue_stance
end

app/models/election.rb
class Election < ActiveRecord::Base
  belongs_to :office
  has_one :organization, :through => :office
  has_many :candidates
  has_many :baselines
  has_many :votes, :through => :candidates
  
  def name
    "#{office.name_organization} - #{self.end_date.strftime("%b %Y")}"
  end
  
  def determine_winner
    tally = {}
    candidates.each do |candidate|
      tally[candidate] = 0
      candidate.votes.current.authorized.each do |vote|
        baseline = vote.voter.baselines.find_by_election_id id
        tally[candidate] = tally[candidate] + 1 if vote.support >= baseline.andand.level.to_i
      end
    end
    @winner = [nil, 0]
    tally.each do |candidate, vote_count|
      @winner = [candidate, vote_count] if vote_count > @winner[1]
    end
    return @winner
  end
  
  def days_left
    ((end_date - DateTime.now) / 1.day).to_i
  end
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  has_many :issue_stances
  has_many :stances, :through => :issue_stances
end

app/models/issue_stance.rb
class IssueStance < ActiveRecord::Base
  belongs_to :issue
  belongs_to :stance
  has_many :candidate_stances
  has_many :candidates, :through => :candidate_stances
  
  scope :on_issue, lambda { |issue| where(:issue_id => issue.id) }
  
  def name
    stance.name + " on " + issue.name
  end
end

app/models/office.rb
class Office < ActiveRecord::Base
  belongs_to :organization
  has_many :elections
  
  def name_organization
    "#{name} of #{organization.name}"
  end
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  has_many :offices
end

app/models/party.rb
class Party < ActiveRecord::Base

end

app/models/stance.rb
class Stance < ActiveRecord::Base
  has_many :issue_stances
  has_many :issues, :through => :issue_stances
  has_many :candidate_stances, :through => :issue_stances
  has_many :candidates, :through => :candidate_stances
  has_many :elections, :through => :candidates
  has_many :offices, :through => :elections
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :candidate
  belongs_to :voter
  
  scope :current, :conditions => {:current => true}
  scope :authorized, where(:authorized => true)
  scope :by, lambda { |voter| {:conditions =>    
    {:voter_id => voter.id}} }
end

app/models/voter.rb
class Voter < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :votes
  has_many :baselines

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/candidate_stances_controller.rb
class CandidateStancesController < ApplicationController
  # GET /candidate_stances
  # GET /candidate_stances.json
  def index
    @candidate_stances = CandidateStance.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @candidate_stances }
    end
  end

  # GET /candidate_stances/1
  # GET /candidate_stances/1.json
  def show
    @candidate_stance = CandidateStance.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @candidate_stance }
    end
  end

  # GET /candidate_stances/new
  # GET /candidate_stances/new.json
  def new
    @candidate_stance = CandidateStance.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @candidate_stance }
    end
  end

  # GET /candidate_stances/1/edit
  def edit
    @candidate_stance = CandidateStance.find(params[:id])
  end

  # POST /candidate_stances
  # POST /candidate_stances.json
  def create
    @candidate_stance = CandidateStance.new(params[:candidate_stance])

    respond_to do |format|
      if @candidate_stance.save
        format.html { redirect_to @candidate_stance, notice: 'Candidate stance was successfully created.' }
        format.json { render json: @candidate_stance, status: :created, location: @candidate_stance }
      else
        format.html { render action: "new" }
        format.json { render json: @candidate_stance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /candidate_stances/1
  # PUT /candidate_stances/1.json
  def update
    @candidate_stance = CandidateStance.find(params[:id])

    respond_to do |format|
      if @candidate_stance.update_attributes(params[:candidate_stance])
        format.html { redirect_to @candidate_stance, notice: 'Candidate stance was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @candidate_stance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /candidate_stances/1
  # DELETE /candidate_stances/1.json
  def destroy
    @candidate_stance = CandidateStance.find(params[:id])
    @candidate_stance.destroy

    respond_to do |format|
      format.html { redirect_to candidate_stances_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_name obj, method = nil
    if method
      link_to obj.send(method), obj rescue nil
    else
      link_to obj.name, obj rescue nil
    end
  end
  
  def blueprints_links
    link_to('generate organization', 'build/org') + ' ' +
    link_to('generate office', 'build/off') + ' ' +
    link_to('generate election', 'build/elec') + ' ' +
    link_to('generate candidate', 'build/cand')
  end
  
  def login_links
    # if logged_in?
      link_to('log out', logout_path)
    # else
      # link_to 'log in', login_path
    # end
  end
end

app/helpers/baselines_helper.rb
module BaselinesHelper
end

app/helpers/candidate_stances_helper.rb
module CandidateStancesHelper
end

app/helpers/candidates_helper.rb
module CandidatesHelper

  def days_until_election candidate
    days = candidate.election.days_left
    "With #{pluralize days, 'day'} left in the election"
  end

  def support_level candidate
    support = candidate.support
    "#{candidate.name} has the support of #{support} percent of voters"
  end
end

app/helpers/elections_helper.rb
module ElectionsHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/helpers/stances_helper.rb
module StancesHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/candidate_stances/_form.html.erb
<%= form_for(@candidate_stance) do |f| %>
  <% if @candidate_stance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@candidate_stance.errors.count, "error") %> prohibited this candidate_stance from being saved:</h2>

      <ul>
      <% @candidate_stance.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :candidate_id %><br />
    <%= f.select :candidate_id, options_from_collection_for_select(Candidate.all, :id, :name_and_office) %>
  </div>
  <div class="field">
    <%= f.label :issue_stance_id %><br />
    <%= f.select :issue_stance_id, options_from_collection_for_select(IssueStance.all, :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/candidate_stances/edit.html.erb
<h1>Editing candidate_stance</h1>

<%= render 'form' %>

<%= link_to 'Show', @candidate_stance %> |
<%= link_to 'Back', candidate_stances_path %>

app/views/candidate_stances/index.html.erb
<h1>Listing candidate_stances</h1>

<table>
  <tr>
    <th>Candidate</th>
    <th>Issue stance</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @candidate_stances.each do |candidate_stance| %>
  <tr>
    <td><%= candidate_stance.candidate %></td>
    <td><%= candidate_stance.issue_stance %></td>
    <td><%= candidate_stance.description %></td>
    <td><%= link_to 'Show', candidate_stance %></td>
    <td><%= link_to 'Edit', edit_candidate_stance_path(candidate_stance) %></td>
    <td><%= link_to 'Destroy', candidate_stance, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Candidate stance', new_candidate_stance_path %>

app/views/candidate_stances/new.html.erb
<h1>New candidate_stance</h1>

<%= render 'form' %>

<%= link_to 'Back', candidate_stances_path %>

app/views/candidate_stances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Candidate:</b>
  <%= link_to_name @candidate_stance.candidate %>
</p>

<p>
  <b>Issue stance:</b>
  <%= link_to_name @candidate_stance.issue_stance %>
</p>

<p>
  <b>Issue:</b>
  <%= link_to_name @candidate_stance.issue %>
</p>

<p>
  <b>Description:</b>
  <%= @candidate_stance.description %>
</p>


<%= link_to 'Edit', edit_candidate_stance_path(@candidate_stance) %> |
<%= link_to 'Back', candidate_stances_path %>