config/routes.rb
Express::Application.routes.draw do
  resources :candidate_stances

  resources :baselines

  resources :votes

  devise_for :voters do
    match '/login' => 'devise/sessions#new', :as => :login
    match '/logout' => 'devise/sessions#destroy', :as => :logout
  end

  resources :issue_stances

  resources :stances

  resources :issues

  resources :parties

  resources :candidates

  resources :elections do
    member do
      get 'poll_results'
    end
    resources :votes
  end

  resources :offices

  resources :organizations
  
  match "build/:action/:id" => "blueprints"
  
  root :to => "elections#index"

end

app/models/stance.rb
class Stance < ActiveRecord::Base
  has_many :issue_stances
  has_many :issues, :through => :issue_stances
  has_many :candidate_stances, :through => :issue_stances
  has_many :candidates, :through => :candidate_stances
  has_many :elections, :through => :candidates
  has_many :offices, :through => :elections
end

app/controllers/stances_controller.rb
class StancesController < ApplicationController
  # GET /stances
  # GET /stances.xml
  def index
    @stances = Stance.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @stances }
    end
  end

  # GET /stances/1
  # GET /stances/1.xml
  def show
    @stance = Stance.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @stance }
    end
  end

  # GET /stances/new
  # GET /stances/new.xml
  def new
    @stance = Stance.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @stance }
    end
  end

  # GET /stances/1/edit
  def edit
    @stance = Stance.find(params[:id])
  end

  # POST /stances
  # POST /stances.xml
  def create
    @stance = Stance.new(params[:stance])

    respond_to do |format|
      if @stance.save
        format.html { redirect_to(@stance, :notice => 'Stance was successfully created.') }
        format.xml  { render :xml => @stance, :status => :created, :location => @stance }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @stance.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /stances/1
  # PUT /stances/1.xml
  def update
    @stance = Stance.find(params[:id])

    respond_to do |format|
      if @stance.update_attributes(params[:stance])
        format.html { redirect_to(@stance, :notice => 'Stance was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @stance.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /stances/1
  # DELETE /stances/1.xml
  def destroy
    @stance = Stance.find(params[:id])
    @stance.destroy

    respond_to do |format|
      format.html { redirect_to(stances_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/stances_helper.rb
module StancesHelper
end

app/views/stances/_form.html.erb
<%= form_for(@stance) do |f| %>
  <% if @stance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stance.errors.count, "error") %> prohibited this stance from being saved:</h2>

      <ul>
      <% @stance.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stances/edit.html.erb
<h1>Editing stance</h1>

<%= render 'form' %>

<%= link_to 'Show', @stance %> |
<%= link_to 'Back', stances_path %>

app/views/stances/index.html.erb
<h1>Listing stances</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @stances.each do |stance| %>
  <tr>
    <td><%= stance.name %></td>
    <td><%= stance.description %></td>
    <td><%= link_to 'Show', stance %></td>
    <td><%= link_to 'Edit', edit_stance_path(stance) %></td>
    <td><%= link_to 'Destroy', stance, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Stance', new_stance_path %>

app/views/stances/new.html.erb
<h1>New stance</h1>

<%= render 'form' %>

<%= link_to 'Back', stances_path %>

app/views/stances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @stance.name %>
</p>

<p>
  <b>Description:</b>
  <%= @stance.description %>
</p>

<h2>Issues to which this stance is applied</h2>
<div id="issues">
  <% @stance.issue_stances.each do |issue_stance| %>
    <%= div_for issue_stance do %>
      <%= link_to_name issue_stance.issue %>
      <%= div_for issue_stance, :candidates_with do %>
        <% issue_stance.candidates.each do |candidate| %>
          <%= div_for candidate do %>
            <%= link_to_name candidate %>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
</div>

<h2>Elections in which this issue is relevant</h2>
<div id="elections">
  <% @stance.elections.each do |election| %>
    <%= div_for election do %>
      <%= link_to_name election %>
    <% end %>
  <% end %>
</div>


<%= link_to 'Edit', edit_stance_path(@stance) %> |
<%= link_to 'Back', stances_path %>